import LontongMedanImg from "../assets/images/kuliner/lontong-medan.png";
import BikaAmbonImg from "../assets/images/kuliner/bika-ambon.png";
import JusMartabeImg from "../assets/images/kuliner/martabe.png";
import UcokDurianImg from "../assets/images/kuliner/ucok-durian.png";

export const culinaryConfig = {
  id: {
    categories: [
      { id: "all", label: "Semua" },
      { id: "berat", label: "Makanan Berat" },
      { id: "camilan", label: "Camilan & Oleh-oleh" },
      { id: "segar", label: "Minuman Segar" },
    ],
    items: [
      {
        id: 1,
        title: "Lontong Medan",
        category: "berat",
        tag: "Makanan Berat",
        isMustTry: true,
        desc: "Perpaduan unik lontong, sayur gulai tauco yang sedap, serta taburan teri kacang dan kerupuk merah yang menciptakan cita rasa gurih-pedas autentik khas Medan.",
        imageUrl: LontongMedanImg,
        gridClass: "col-span-12 lg:col-span-7 aspect-[4/3] lg:aspect-auto lg:h-full",
        rating: 4.7,
        address: "Jl. Kejaksaan, Kesawan, Medan",
        hours: "Buka 06.00 - 22.00 WIB (Setiap Hari)",
        priceRange: "Rp 15.000 - Rp 30.000 / porsi",
        facilities: "Dine-in, Takeaway, Area Parkir Motor",
        gallery: [LontongMedanImg, LontongMedanImg, LontongMedanImg],
      },
      {
        id: 2,
        title: "Bika Ambon",
        category: "camilan",
        tag: "Camilan",
        isMustTry: false,
        desc: "Kue basah tradisional bertekstur rongga semut dengan rasa pandan wangi.",
        imageUrl: BikaAmbonImg,
        gridClass: "col-span-12 sm:col-span-6 lg:col-span-5 aspect-[4/3] lg:aspect-auto",
        rating: 4.6,
        address: "Jl. Mojopahit, Medan",
        hours: "Buka 08.00 - 21.00 WIB (Setiap Hari)",
        priceRange: "Rp 45.000 - Rp 90.000 / kotak",
        facilities: "Takeaway, Packaging Oleh-oleh, Area Parkir",
        gallery: [BikaAmbonImg],
      },
      {
        id: 3,
        title: "Jus Martabe",
        category: "segar",
        tag: "Minuman",
        isMustTry: false,
        desc: "Kombinasi segar buah markisa asli dan terong belanda khas Sumatra Utara.",
        imageUrl: JusMartabeImg,
        gridClass: "col-span-12 sm:col-span-6 lg:col-span-5 aspect-[4/3] lg:aspect-auto",
        rating: 4.5,
        address: "Jl. Sei Batang Serangan, Medan",
        hours: "Buka 09.00 - 20.00 WIB (Setiap Hari)",
        priceRange: "Rp 15.000 - Rp 25.000 / gelas",
        facilities: "Dine-in, Takeaway",
        gallery: [JusMartabeImg],
      },
      {
        id: 4,
        title: "Ucok Durian",
        category: "camilan",
        tag: "Ikonik",
        isMustTry: false,
        desc: "Raja durian dengan kualitas premium yang mendunia.",
        imageUrl: UcokDurianImg,
        gridClass: "col-span-12 lg:col-span-7 aspect-[16/9] lg:aspect-auto",
        rating: 4.8,
        address: "Jl. K.H. Wahid Hasyim No.30-32, Medan",
        hours: "Buka 24 Jam (Setiap Hari)",
        priceRange: "Rp 50.000 - Rp 150.000 / orang",
        facilities: "Area Parkir Luas, Dine-in, Takeaway, Packaging Pesawat",
        gallery: [UcokDurianImg],
      },
    ],
  },
  en: {
    categories: [
      { id: "all", label: "All" },
      { id: "berat", label: "Main Course" },
      { id: "camilan", label: "Snacks & Local Gifts" },
      { id: "segar", label: "Fresh Drinks" },
    ],
    items: [
      {
        id: 1,
        title: "Lontong Medan",
        category: "berat",
        tag: "Main Course",
        isMustTry: true,
        desc: "A unique blend of rice cakes, savory tauco curry, topped with peanuts, anchovies, and red crackers creating Medan's authentic savory-spicy flavor.",
        imageUrl: LontongMedanImg,
        gridClass: "col-span-12 lg:col-span-7 aspect-[4/3] lg:aspect-auto lg:h-full",
        rating: 4.7,
        address: "Jl. Kejaksaan, Kesawan, Medan",
        hours: "Open 06.00 - 22.00 WIB (Everyday)",
        priceRange: "Rp 15.000 - Rp 30.000 / portion",
        facilities: "Dine-in, Takeaway, Motorcycle Parking Area",
        gallery: [LontongMedanImg, LontongMedanImg, LontongMedanImg],
      },
      {
        id: 2,
        title: "Bika Ambon (traditional golden cake)",
        category: "camilan",
        tag: "Snack",
        isMustTry: false,
        desc: "Traditional wet cake with an ant-nest cavity texture and fragrant pandan flavor.",
        imageUrl: BikaAmbonImg,
        gridClass: "col-span-12 sm:col-span-6 lg:col-span-5 aspect-[4/3] lg:aspect-auto",
        rating: 4.6,
        address: "Jl. Mojopahit, Medan",
        hours: "Open 08.00 - 21.00 WIB (Everyday)",
        priceRange: "Rp 45.000 - Rp 90.000 / box",
        facilities: "Takeaway, Souvenir Packaging, Parking Area",
        gallery: [BikaAmbonImg],
      },
      {
        id: 3,
        title: "Jus Martabe",
        category: "segar",
        tag: "Drink",
        isMustTry: false,
        desc: "A fresh combination of original passion fruit and tamarillo native to North Sumatra.",
        imageUrl: JusMartabeImg,
        gridClass: "col-span-12 sm:col-span-6 lg:col-span-5 aspect-[4/3] lg:aspect-auto",
        rating: 4.5,
        address: "Jl. Sei Batang Serangan, Medan",
        hours: "Open 09.00 - 20.00 WIB (Everyday)",
        priceRange: "Rp 15.000 - Rp 25.000 / glass",
        facilities: "Dine-in, Takeaway",
        gallery: [JusMartabeImg],
      },
      {
        id: 4,
        title: "Ucok Durian",
        category: "camilan",
        tag: "Iconic",
        isMustTry: false,
        desc: "The king of durian with globally recognized premium quality.",
        imageUrl: UcokDurianImg,
        gridClass: "col-span-12 lg:col-span-7 aspect-[16/9] lg:aspect-auto",
        rating: 4.8,
        address: "Jl. K.H. Wahid Hasyim No.30-32, Medan",
        hours: "Open 24 Hours (Everyday)",
        priceRange: "Rp 50.000 - Rp 150.000 / person",
        facilities: "Large Parking Area, Dine-in, Takeaway, Flight Packaging",
        gallery: [UcokDurianImg],
      },
    ],
  }
};