import BusImage from "../assets/images/Teknologi-Modern/bus-listrik.jpg";
import RuteImage from "../assets/images/Teknologi-Modern/rute.jpg";

export const infraConfig = {
  id: {
    header: "INFRASTRUKTUR & MOBILITAS",
    title: "Konektivitas Tanpa Batas",
    mainCard: {
      slug: "bus-listrik-medan",
      title: "Inisiatif Bus Listrik 2024",
      desc: "Langkah nyata Kota Medan menuju transportasi umum masa depan yang bebas emisi, ramah lingkungan, dan berbasis teknologi modern.",
      image: BusImage,
      category: "Mobilitas Cerdas",
      date: "Transportasi rendah emisi",
      location: "Koridor utama Kota Medan",
      highlight: "Bus listrik menjadi simbol peralihan Medan menuju transportasi umum yang lebih bersih, nyaman, dan terhubung dengan kebutuhan mobilitas warga.",
      content: [
        "Inisiatif bus listrik memperkenalkan arah baru transportasi publik di Medan. Armada rendah emisi ini dirancang untuk mengurangi polusi perkotaan sekaligus memperbaiki pengalaman perjalanan harian warga.",
        "Teknologi kendaraan listrik memungkinkan operasional yang lebih senyap dan efisien dibandingkan kendaraan berbahan bakar fosil. Jika terintegrasi dengan halte, rute, dan informasi jadwal yang baik, dampaknya dapat terasa langsung pada produktivitas mobilitas kota.",
        "Program ini juga menjadi pintu masuk bagi pengembangan ekosistem pendukung seperti stasiun pengisian, manajemen armada berbasis data, dan integrasi pembayaran digital.",
      ],
      news: [
        "Penguatan transportasi umum rendah emisi.",
        "Rencana pengoperasian bertahap pada koridor utama.",
        "Peluang integrasi data rute dan pembayaran digital.",
      ],
    },
    statsCard: {
      slug: "target-60-bus-listrik",
      title: "60 Unit Bus Listrik",
      desc: "Target armada ramah lingkungan yang dikerahkan secara bertahap untuk melayani berbagai koridor utama di Medan.",
      image: BusImage,
      category: "Mobilitas Cerdas",
      date: "Target pengembangan armada",
      location: "Kota Medan",
      highlight: "Target armada listrik menunjukkan komitmen bertahap untuk memperluas layanan transportasi publik yang lebih ramah lingkungan.",
      content: [
        "Target 60 unit bus listrik menjadi indikator keseriusan Medan dalam membangun transportasi publik masa depan. Jumlah armada yang memadai penting agar layanan tidak hanya menjadi proyek percontohan, tetapi benar-benar dipakai warga.",
        "Pengoperasian bertahap memberi ruang bagi pemerintah kota untuk mengevaluasi rute, tingkat keterisian, kebutuhan pengisian daya, serta kebiasaan perjalanan masyarakat.",
        "Jika didukung informasi jadwal yang jelas dan akses halte yang nyaman, armada listrik dapat menjadi alternatif harian bagi pelajar, pekerja, dan pengunjung kota.",
      ],
      news: [
        "Pengerahan armada dilakukan secara bertahap.",
        "Evaluasi rute menjadi bagian penting dari pengembangan layanan.",
        "Transportasi publik menjadi fondasi smart mobility Medan.",
      ],
    },
    mapCard: {
      slug: "rute-terintegrasi-medan",
      title: "Rute Terintegrasi",
      image: RuteImage,
      desc: "Perencanaan rute yang menghubungkan titik penting kota agar perjalanan publik menjadi lebih mudah dipahami dan efisien.",
      category: "Konektivitas Kota",
      date: "Integrasi jaringan mobilitas",
      location: "Kota Medan",
      highlight: "Rute terintegrasi membantu warga berpindah antarkawasan dengan informasi perjalanan yang lebih jelas dan layanan yang saling tersambung.",
      content: [
        "Rute terintegrasi adalah fondasi penting bagi transportasi perkotaan. Di Medan, pendekatan ini dapat menghubungkan pusat bisnis, kawasan pendidikan, pasar, terminal, dan destinasi publik dalam jaringan perjalanan yang lebih mudah dibaca.",
        "Integrasi rute tidak hanya soal jalur kendaraan, tetapi juga informasi. Peta, jadwal, titik transit, dan opsi pembayaran perlu hadir secara konsisten agar warga percaya menggunakan transportasi umum.",
        "Ketika rute saling tersambung, kota dapat mengurangi ketergantungan pada kendaraan pribadi dan menciptakan ruang jalan yang lebih efisien.",
      ],
      news: [
        "Konektivitas antarkawasan menjadi fokus mobilitas kota.",
        "Informasi rute digital membantu warga merencanakan perjalanan.",
        "Integrasi transportasi mendukung pengurangan kemacetan.",
      ],
    },
  },
  en: {
    header: "INFRASTRUCTURE & MOBILITY",
    title: "Boundless Connectivity",
    mainCard: {
      slug: "bus-listrik-medan",
      title: "2024 Electric Bus Initiative",
      desc: "A concrete step by Medan City towards a future public transportation system that is emission-free, environmentally friendly, and based on modern technology.",
      image: BusImage,
      category: "Smart Mobility",
      date: "Low-emission transportation",
      location: "Main corridors of Medan City",
      highlight: "Electric buses become a symbol of Medan's transition to cleaner, more comfortable public transportation connected to residents' mobility needs.",
      content: [
        "The electric bus initiative introduces a new direction for public transportation in Medan. This low-emission fleet is designed to reduce urban pollution while improving the daily travel experience of residents.",
        "Electric vehicle technology allows for quieter and more efficient operations compared to fossil fuel vehicles. When integrated with stops, routes, and good schedule information, the impact can be felt directly on city mobility productivity.",
        "This program also serves as an entry point for developing a supporting ecosystem such as charging stations, data-based fleet management, and digital payment integration.",
      ],
      news: [
        "Strengthening low-emission public transportation.",
        "Plans for phased operation on main corridors.",
        "Opportunities for route data and digital payment integration.",
      ],
    },
    statsCard: {
      slug: "target-60-bus-listrik",
      title: "60 Electric Bus Units",
      desc: "Target eco-friendly fleet deployed in phases to serve various main corridors in Medan.",
      image: BusImage,
      category: "Smart Mobility",
      date: "Fleet development target",
      location: "Medan City",
      highlight: "The electric fleet target demonstrates a phased commitment to expanding more environmentally friendly public transportation services.",
      content: [
        "The target of 60 electric bus units is an indicator of Medan's seriousness in building future public transportation. An adequate fleet is important so that the service is not just a pilot project but is actually used by residents.",
        "Phased operation gives the city government room to evaluate routes, occupancy rates, charging needs, and community travel habits.",
        "If supported by clear schedule information and convenient stop access, the electric fleet can become a daily alternative for students, workers, and city visitors.",
      ],
      news: [
        "Fleet deployment carried out in phases.",
        "Route evaluation is an important part of service development.",
        "Public transportation becomes the foundation of Medan's smart mobility.",
      ],
    },
    mapCard: {
      slug: "rute-terintegrasi-medan",
      title: "Integrated Routes",
      image: RuteImage,
      desc: "Route planning that connects important city points to make public journeys easier to understand and more efficient.",
      category: "City Connectivity",
      date: "Mobility network integration",
      location: "Medan City",
      highlight: "Integrated routes help residents move between areas with clearer travel information and interconnected services.",
      content: [
        "Integrated routes are an important foundation for urban transportation. In Medan, this approach can connect business centers, educational areas, markets, terminals, and public destinations in a more readable travel network.",
        "Route integration is not just about vehicle lanes, but also information. Maps, schedules, transit points, and payment options need to be consistently available so residents trust public transportation.",
        "When routes are interconnected, the city can reduce dependence on private vehicles and create more efficient road space.",
      ],
      news: [
        "Connectivity between areas becomes the focus of city mobility.",
        "Digital route information helps residents plan their journeys.",
        "Transportation integration supports congestion reduction.",
      ],
    },
  },
};
